-- =============================================================================
-- Text Search
-- =============================================================================
--
-- Search is handled by Meilisearch (external sidecar), not by a Postgres index.
-- The pg_trgm GIN index on properties::text was removed because:
--   - 110-170 GB at enterprise scale (2-3x properties column size)
--   - Write amplification on every INSERT/UPDATE
--   - Indexed JSON structural noise (keys, braces, colons)
--   - No relevance ranking, stemming, or typo tolerance
--
-- Meilisearch indexes only searchable text (label, description, note).
-- Postgres RLS remains the final backstop on all fetches.
--
-- =============================================================================
